##########################################################
# This file is part of the NovaGames plugin by EasyMFnE. #
##########################################################

###########################################
# MINIGAME CONFIGURATION LAYOUT:          #
#=========================================#
# minigame_name_key:                      #
#   'minigame.component.class.name':      #
#     minigame_setting_1: "Some setting"  #
#     minigame_setting_2: true            #
#=========================================#
# Notes:                                  #
# - Component class names not containing  #
#   any "." symbols will be prepended w/  #
#   "net.easymfne.novagames.component."   #
#   for simpler listing of components     #
#   that come packaged within the plugin. #
###########################################
minigames:

  example_minigame:
    'Basics':
      pvp: false
      pve: false
    'Spectation':
      spawn: "world, 0.0, 64.0, 0.0, 180.0, 0.0"
      visible: false
